# Generated by Django 5.0.4 on 2025-01-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('job_department', models.CharField(choices=[('production department', 'Production Department'), ('research & development department', 'Research & Development Department'), ('quality assurance', 'Quality Assurance'), ('quality control', 'Quality Control'), ('maintance department', 'Maintenance Department'), ('finance department', 'Finance Department'), ('E-marketing department', 'E-Marketing Department')], max_length=100)),
                ('job_description', models.TextField()),
                ('job_photo', models.ImageField(upload_to='job_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
