# Generated by Django 5.1.4 on 2025-05-13 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('job_department', models.CharField(choices=[('production department', 'Production Department'), ('research & development department', 'Research & Development Department'), ('quality assurance', 'Quality Assurance'), ('quality control', 'Quality Control'), ('maintance department', 'Maintenance Department'), ('finance department', 'Finance Department'), ('E-marketing department', 'E-Marketing Department')], max_length=100)),
                ('job_description', models.TextField()),
                ('job_location', models.CharField(choices=[('edlib', 'Edlib'), ('hama', 'Hama'), ('aleppo', 'Aleppo'), ('homs', 'Homs'), ('damascus', 'Damascus'), ('latakia', 'Latakia'), ('tartous', 'Tartous')], default='damascus', max_length=100)),
                ('job_photo', models.ImageField(upload_to='job_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobApplicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('birth_date', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('marital_status', models.CharField(max_length=10)),
                ('scientific_certificate', models.CharField(max_length=255)),
                ('specialization', models.CharField(max_length=255)),
                ('is_graduate', models.CharField(max_length=10)),
                ('graduation_institution', models.CharField(blank=True, max_length=255, null=True)),
                ('experiences', models.TextField(blank=True, null=True)),
                ('has_health_issues', models.CharField(max_length=10)),
                ('health_issue_description', models.TextField(blank=True, null=True)),
                ('previous_application', models.CharField(max_length=10)),
                ('previous_application_date', models.DateField(blank=True, null=True)),
                ('has_relatives', models.CharField(max_length=10)),
                ('relative_name', models.CharField(blank=True, max_length=255, null=True)),
                ('relative_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('cv_file', models.FileField(upload_to='cvs/')),
                ('id_file', models.FileField(upload_to='ids/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicants', to='job_vacancies.jobapplication')),
            ],
        ),
    ]
