# Generated by Django 5.1.4 on 2025-05-13 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplicant',
            name='birth_place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='current_residence',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobapplicant',
            name='phone_backup',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
