# Generated by Django 5.0.4 on 2025-01-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_vacancies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='job_location',
            field=models.CharField(default='Riyadh', max_length=100),
        ),
    ]
