# Generated by Django 5.0.4 on 2025-01-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_vacancies', '0002_jobapplication_job_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='job_location',
            field=models.CharField(choices=[('adlib', 'Adlib'), ('hama', 'Hama'), ('aleppo', 'Aleppo'), ('homs', 'Homs'), ('damascus', 'Damascus'), ('latakia', 'Latakia'), ('tartous', 'Tartous')], default='damascus', max_length=100),
        ),
    ]
