# Generated by Django 5.0.4 on 2025-01-20 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_vacancies', '0003_alter_jobapplication_job_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('father_name', models.CharField(max_length=100)),
                ('mother_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('birth_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneralInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_application', models.BooleanField(default=False)),
                ('previous_application_date', models.DateField(blank=True, null=True)),
                ('health_problems', models.BooleanField(default=False)),
                ('health_problems_details', models.TextField(blank=True)),
                ('is_smoker', models.BooleanField(default=False)),
                ('has_relatives', models.BooleanField(default=False)),
                ('relative_name', models.CharField(blank=True, max_length=100)),
                ('relative_phone', models.CharField(blank=True, max_length=20)),
                ('additional_information', models.TextField(blank=True)),
                ('personal_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job_vacancies.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('id_number', models.CharField(max_length=50)),
                ('address', models.TextField()),
                ('marital_status', models.CharField(max_length=10)),
                ('number_of_children', models.IntegerField(blank=True, null=True)),
                ('personal_info', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='job_vacancies.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_name', models.CharField(max_length=200)),
                ('specialization', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('average', models.DecimalField(decimal_places=2, max_digits=5)),
                ('graduation_date', models.DateField()),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_vacancies.personalinfo')),
            ],
        ),
    ]
