# Generated by Django 5.0.4 on 2025-02-24 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False, verbose_name='رقم الشكوى')),
                ('name', models.CharField(max_length=100, verbose_name='اسم مقدم الشكوى')),
                ('email', models.EmailField(max_length=254, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('report_type', models.CharField(choices=[('our_product', 'شكوى على منتج'), ('our_team', 'شكوى على موظف')], max_length=20, verbose_name='نوع الشكوى')),
                ('complainant_type', models.CharField(choices=[('doctor', 'طبيب'), ('pharmacist', 'صيدلي'), ('patient', 'مريض'), ('other', 'آخر')], max_length=20, verbose_name='المكانة الطبية')),
                ('description', models.TextField(verbose_name='تفاصيل الشكوى')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ ووقت الشكوى')),
            ],
            options={
                'verbose_name': 'تقرير',
                'verbose_name_plural': 'التقارير',
                'ordering': ['-created_at'],
            },
        ),
    ]
