# Generated by Django 5.0.4 on 2025-01-06 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('pro_type', models.CharField(max_length=50, verbose_name='Product Type')),
                ('pro_description', models.TextField(verbose_name='Product Description')),
                ('pro_composition', models.TextField(verbose_name='Product Composition')),
                ('pro_photo', models.ImageField(upload_to='products/', verbose_name='Product Photo')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
