# Generated by Django 5.0.4 on 2025-02-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id_pro', models.BigAutoField(primary_key=True, serialize=False)),
                ('pro_name', models.CharField(max_length=100, verbose_name='Product Name')),
                ('pro_type', models.CharField(choices=[('Oral Suspension', 'Oral Suspension'), ('Capsule', 'Capsule'), ('tablets', 'Tablets'), ('Syrup', 'Syrup'), ('Suppositories', 'Suppositories')], max_length=50, verbose_name='Product Type')),
                ('pro_Therapeutic_Category', models.CharField(blank=True, max_length=200, null=True, verbose_name='Therapeutic Category')),
                ('pro_photo', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Product Photo')),
                ('pro_composition', models.TextField(blank=True, null=True, verbose_name='Product Composition')),
                ('pro_Indications', models.TextField(blank=True, null=True, verbose_name='Indications')),
                ('pro_Contraindications', models.TextField(blank=True, null=True, verbose_name='Contraindications')),
                ('pro_Drug_Interactions', models.TextField(blank=True, null=True, verbose_name='Drug Interactions')),
                ('pro_pregnancy_lactation', models.TextField(blank=True, null=True, verbose_name='Pregnancy and Lactation')),
                ('pro_dosage_administration', models.TextField(blank=True, null=True, verbose_name='Dosage and Administration')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
