# Generated by Django 5.0.4 on 2025-02-24 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_pro_therapeutic_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pro_type',
            field=models.CharField(choices=[('Oral Suspension', 'Oral Suspension'), ('Capsule', 'Capsule'), ('tablets', 'Tablets'), ('Syrup', 'Syrup'), ('Suppositories', 'Suppositories'), ('Oral Drops', 'Oral Drops')], max_length=50, verbose_name='Product Type'),
        ),
    ]
