# Generated by Django 5.1.4 on 2025-05-25 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_products_pro_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='product_pdfs/'),
        ),
    ]
