# Generated by Django 5.1.4 on 2025-06-02 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_products_pdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='pro_Contraindications',
        ),
        migrations.RemoveField(
            model_name='products',
            name='pro_Drug_Interactions',
        ),
        migrations.RemoveField(
            model_name='products',
            name='pro_Indications',
        ),
        migrations.RemoveField(
            model_name='products',
            name='pro_composition',
        ),
        migrations.RemoveField(
            model_name='products',
            name='pro_dosage_administration',
        ),
        migrations.RemoveField(
            model_name='products',
            name='pro_name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='pro_photo',
        ),
        migrations.RemoveField(
            model_name='products',
            name='pro_pregnancy_lactation',
        ),
        migrations.AddField(
            model_name='products',
            name='pro_Contraindications_ar',
            field=models.TextField(blank=True, null=True, verbose_name='موانع الاستعمال (AR)'),
        ),
        migrations.AddField(
            model_name='products',
            name='pro_Contraindications_en',
            field=models.TextField(blank=True, null=True, verbose_name='Contraindications (EN)'),
        ),
        migrations.AddField(
            model_name='products',
            name='pro_Drug_Interactions_ar',
            field=models.TextField(blank=True, null=True, verbose_name='التداخلات الدوائية (AR)'),
        ),
        migrations.AddField(
            model_name='products',
            name='pro_Drug_Interactions_en',
            field=models.TextField(blank=True, null=True, verbose_name='Drug Interactions (EN)'),
        ),
        migrations.AddField(
            model_name='products',
            name='pro_Indications_ar',
            field=models.TextField(blank=True, null=True, verbose_name='الاستطبابات (AR)'),
        ),
        migrations.AddField(
            model_name='products',
            name='pro_Indications_en',
            field=models.TextField(blank=True, null=True, verbose_name='Indications (EN)'),
        ),
        migrations.AddField(
            model_name='products',
            name='pro_composition_ar',
            field=models.TextField(blank=True, null=True, verbose_name='التركيب (AR)'),
        ),
        migrations.AddField(
            model_name='products',
            name='pro_composition_en',
            field=models.TextField(blank=True, null=True, verbose_name='Composition (EN)'),
        ),
        migrations.AddField(
            model_name='products',
            name='pro_dosage_administration_ar',
            field=models.TextField(blank=True, null=True, verbose_name='الجرعة وطريقة الاستعمال (AR)'),
        ),
        migrations.AddField(
            model_name='products',
            name='pro_dosage_administration_en',
            field=models.TextField(blank=True, null=True, verbose_name='Dosage & Administration (EN)'),
        ),
        migrations.AddField(
            model_name='products',
            name='pro_name_ar',
            field=models.CharField(default='null', max_length=100, verbose_name='اسم المنتج (AR)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='pro_name_en',
            field=models.CharField(default='null', max_length=100, verbose_name='Product Name (EN)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='pro_photo_ar',
            field=models.ImageField(blank=True, null=True, upload_to='products/ar/', verbose_name='الصورة (AR)'),
        ),
        migrations.AddField(
            model_name='products',
            name='pro_photo_en',
            field=models.ImageField(blank=True, null=True, upload_to='products/en/', verbose_name='Image (EN)'),
        ),
        migrations.AddField(
            model_name='products',
            name='pro_pregnancy_lactation_ar',
            field=models.TextField(blank=True, null=True, verbose_name='الحمل والرضاعة (AR)'),
        ),
        migrations.AddField(
            model_name='products',
            name='pro_pregnancy_lactation_en',
            field=models.TextField(blank=True, null=True, verbose_name='Pregnancy & Lactation (EN)'),
        ),
    ]
